# Jose Rodrigues Filho
# v1.0
version: '3.5'

services:
#
# Zabbix-Mysql
#
   zabbix_mysql:
    container_name: Zabbix-Mysql
    # Versao (5.7)  
    image: mysql:5.7

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro" 
      - "/home/joserf/docker/containers/zabbix/mysql/data:/var/lib/mysql"

    environment:
       MYSQL_DATABASE: "zabbix"
       MYSQL_USER: "zabbix"
       MYSQL_PASSWORD: "zabbix_password"
       MYSQL_ROOT_PASSWORD: "123456"
       DB_SERVER_PORT: "3306"

    ports:
      - "3307:3306"  

    networks:
      - monitoramentoZABBIX
#   "no", always, on-failure, unless-stopped      
    restart:
      always
#
# Zabbix-Server
#
   zabbix_server:
    container_name: Zabbix-Server
    image: zabbix/zabbix-server-mysql:latest
    # Instala os pacotes necessarios. 
    #command: "apk upgrade --no-cache build-base python3 python3-dev nmap && apk add --update --no-cache tg curl py-pip speedtest-cli && pip install pyTelegramBotAPI && pip install --upgrade pip && rm -rf /usr/share/man /tmp/* /var/cache/apk/*"

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro" 
    # Pasta de scripts.  
      - "/home/joserf/docker/containers/zabbix/scripts:/etc/zabbix/scripts"
      - "/home/joserf/docker/containers/zabbix/alertscripts:/usr/lib/zabbix/alertscripts"

    environment:
       DB_SERVER_HOST: "Zabbix-Mysql"
       MYSQL_DATABASE: "zabbix"
       MYSQL_USER: "zabbix"
       MYSQL_PASSWORD: "zabbix_password"
       MYSQL_ROOT_PASSWORD: "123456"
       DB_SERVER_PORT: "3306"
       ZBX_DEBUGLEVEL: "3"
       ZBX_CACHESIZE: "2G"

    ports:
      - "10051:10051"  

    networks:
      - monitoramentoZABBIX
#   "no", always, on-failure, unless-stopped      
    restart:
      always
#
# Zabbix-Agent
#
   zabbix_agent:
    container_name: Zabbix-Agent
    image: zabbix/zabbix-agent:latest

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro" 

    environment:
       ZBX_HOSTNAME: "Zabbix-Agent"
       ZBX_SERVER_HOST: "Zabbix-Server"
       ZBX_DEBUGLEVEL: "3"
      
    networks:
      - monitoramentoZABBIX
#   "no", always, on-failure, unless-stopped      
    restart:
      always
#
# Zabbix-Web
#
   zabbix_web:
    container_name: Zabbix-Web
    image: zabbix/zabbix-web-apache-mysql:latest

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro" 

    environment:
       DB_SERVER_HOST: "Zabbix-Mysql"
       MYSQL_DATABASE: "zabbix"
       MYSQL_USER: "zabbix"
       MYSQL_PASSWORD: "zabbix_password"
       MYSQL_ROOT_PASSWORD: "123456"
       DB_SERVER_PORT: "3306"
       ZBX_SERVER_NAME: "Nome da Empresa"
       PHP_TZ: "America/Santiago"
       ZBX_HOSTNAME: "`hostname`"
       ZBX_SERVER_HOST: "Zabbix-Server"

    ports:
      - "8282:80"  

    networks:
      - monitoramentoZABBIX
#   "no", always, on-failure, unless-stopped      
    restart:
      always
#
# Grafana
#
   grafana:
    container_name: Grafana
    # Versao (6.5.2)
    image: grafana/grafana

    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/home/joserf/docker/containers/grafana/data:/var/lib/grafana"      

    environment:
       GF_SECURITY_ADMIN_PASSWORD: "123456" 
       GF_INSTALL_PLUGINS: "camptocamp-prometheus-alertmanager-datasource,grafana-clock-panel,briangann-gauge-panel,alexanderzobnin-zabbix-app,farski-blendstat-panel,grafana-polystat-panel,vonage-status-panel,grafana-piechart-panel,mtanda-histogram-panel,yesoreyeram-boomtable-panel" 
       GF_SERVER_PROTOCOL: "http"  
       GF_SERVER_HTTP_PORT: "3000" 
       GF_PANELS_ENABLE_ALPHA: "true" 
       GF_SMTP_ENABLED: "true" 
       GF_SMTP_HOST=smtp.gmail.com: "587"  
       GF_SMTP_USER: "e-mail@gmail.com" 
       GF_SMTP_PASSWORD: "senha"
       # ANONYMOUS
       GF_AUTH_ANONYMOUS_ENABLED: "true"
     
    ports:
      - "3000:3000"

    networks:
      - monitoramentoZABBIX
    # "no", always, on-failure, unless-stopped      
    restart: 
      on-failure:3
#
# NETWORK
#
networks:
  monitoramentoZABBIX:
   name: monitoramentoZABBIX
